name: deploy
on:
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: monitor.devuilewok.be
        username: jitse-server
        key: ${{ secrets.SSH_SECRET }}
        script: |
          cd mush-id
          git pull
          ./restart
